#!/bin/bash
docker run --rm   -v /home/tyj566/mnt/h/lsp-analysis/tyler/jasonSingleCell:/data   -v /data/trm-sc-analysis/data/external:/ref   velocyto:latest run     -b /data/BRI-2937/per_sample_outs/2/count/sample_filtered_feature_bc_matrix/barcodes.tsv.gz     /data/BRI-2937/per_sample_outs/2/count/sample_alignments.bam     /ref/Mus_musculus.GRCm38.93.gtf;
docker run --rm   -v /home/tyj566/mnt/h/lsp-analysis/tyler/jasonSingleCell:/data   -v /data/trm-sc-analysis/data/external:/ref   velocyto:latest run     -b /data/BRI-2937/per_sample_outs/3/count/sample_filtered_feature_bc_matrix/barcodes.tsv.gz     /data/BRI-2937/per_sample_outs/3/count/sample_alignments.bam     /ref/Mus_musculus.GRCm38.93.gtf;
docker run --rm   -v /home/tyj566/mnt/h/lsp-analysis/tyler/jasonSingleCell:/data   -v /data/trm-sc-analysis/data/external:/ref   velocyto:latest run     -b /data/BRI-2937/per_sample_outs/4/count/sample_filtered_feature_bc_matrix/barcodes.tsv.gz     /data/BRI-2937/per_sample_outs/4/count/sample_alignments.bam     /ref/Mus_musculus.GRCm38.93.gtf;
docker run --rm   -v /home/tyj566/mnt/h/lsp-analysis/tyler/jasonSingleCell:/data   -v /data/trm-sc-analysis/data/external:/ref   velocyto:latest run     -b /data/BRI-2937/per_sample_outs/1/count/sample_filtered_feature_bc_matrix/barcodes.tsv.gz     /data/BRI-2937/per_sample_outs/1/count/sample_alignments.bam     /ref/Mus_musculus.GRCm38.93.gtf;
docker run --rm   -v /home/tyj566/mnt/h/lsp-analysis/tyler/jasonSingleCell:/data   -v /data/trm-sc-analysis/data/external:/ref   velocyto:latest run     -b /data/BRI-2939/per_sample_outs/6/count/sample_filtered_feature_bc_matrix/barcodes.tsv.gz     /data/BRI-2939/per_sample_outs/6/count/sample_alignments.bam     /ref/Mus_musculus.GRCm38.93.gtf;
docker run --rm   -v /home/tyj566/mnt/h/lsp-analysis/tyler/jasonSingleCell:/data   -v /data/trm-sc-analysis/data/external:/ref   velocyto:latest run     -b /data/BRI-2939/per_sample_outs/8/count/sample_filtered_feature_bc_matrix/barcodes.tsv.gz     /data/BRI-2939/per_sample_outs/8/count/sample_alignments.bam     /ref/Mus_musculus.GRCm38.93.gtf;
docker run --rm   -v /home/tyj566/mnt/h/lsp-analysis/tyler/jasonSingleCell:/data   -v /data/trm-sc-analysis/data/external:/ref   velocyto:latest run     -b /data/BRI-2939/per_sample_outs/5/count/sample_filtered_feature_bc_matrix/barcodes.tsv.gz     /data/BRI-2939/per_sample_outs/5/count/sample_alignments.bam     /ref/Mus_musculus.GRCm38.93.gtf;
docker run --rm   -v /home/tyj566/mnt/h/lsp-analysis/tyler/jasonSingleCell:/data   -v /data/trm-sc-analysis/data/external:/ref   velocyto:latest run     -b /data/BRI-2939/per_sample_outs/7/count/sample_filtered_feature_bc_matrix/barcodes.tsv.gz     /data/BRI-2939/per_sample_outs/7/count/sample_alignments.bam     /ref/Mus_musculus.GRCm38.93.gtf;
docker run --rm   -v /home/tyj566/mnt/h/lsp-analysis/tyler/jasonSingleCell:/data   -v /data/trm-sc-analysis/data/external:/ref   velocyto:latest run     -b /data/BRI-2941/per_sample_outs/11/count/sample_filtered_feature_bc_matrix/barcodes.tsv.gz     /data/BRI-2941/per_sample_outs/11/count/sample_alignments.bam     /ref/Mus_musculus.GRCm38.93.gtf;
docker run --rm   -v /home/tyj566/mnt/h/lsp-analysis/tyler/jasonSingleCell:/data   -v /data/trm-sc-analysis/data/external:/ref   velocyto:latest run     -b /data/BRI-2941/per_sample_outs/12/count/sample_filtered_feature_bc_matrix/barcodes.tsv.gz     /data/BRI-2941/per_sample_outs/12/count/sample_alignments.bam     /ref/Mus_musculus.GRCm38.93.gtf;
docker run --rm   -v /home/tyj566/mnt/h/lsp-analysis/tyler/jasonSingleCell:/data   -v /data/trm-sc-analysis/data/external:/ref   velocyto:latest run     -b /data/BRI-2941/per_sample_outs/9/count/sample_filtered_feature_bc_matrix/barcodes.tsv.gz     /data/BRI-2941/per_sample_outs/9/count/sample_alignments.bam     /ref/Mus_musculus.GRCm38.93.gtf;
docker run --rm   -v /home/tyj566/mnt/h/lsp-analysis/tyler/jasonSingleCell:/data   -v /data/trm-sc-analysis/data/external:/ref   velocyto:latest run     -b /data/BRI-2941/per_sample_outs/10/count/sample_filtered_feature_bc_matrix/barcodes.tsv.gz     /data/BRI-2941/per_sample_outs/10/count/sample_alignments.bam     /ref/Mus_musculus.GRCm38.93.gtf